import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Toaster } from "sonner";

import "./globals.css";
import { QueryClientProviderClient } from "@/lib/react-query/provider-client";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Challenge | Base Exchange",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className}`}
      >
        <QueryClientProviderClient>
          {children}
          <Toaster position='top-right' richColors expand={true} />
        </QueryClientProviderClient>
      </body>
    </html>
  );
}
